package main.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Controller for the Main Menu (main-view.fxml).
 * Handles navigation to other screens in the SAME window.
 */
public class MainController {

    /**
     * Helper method to switch the current window (Stage) to display a new FXML view.
     * The method preserves the current window size and applies the shared stylesheet.
     *
     * @param fxmlFile the name of the FXML file to load, from the resources root
     * @param title    the title to set on the Stage after switching views
     * @param event    the action event triggered by the button click
     */
    private void switchView(String fxmlFile, String title, ActionEvent event) {
        try {
            // All your FXML files are at the root of resources: /coffee-view.fxml, etc.
            Parent root = FXMLLoader.load(getClass().getResource("/" + fxmlFile));

            Stage stage = (Stage) ((Node) event.getSource())
                    .getScene().getWindow();
            
            // Preserve window size
            double width = stage.getWidth();
            double height = stage.getHeight();
            
            Scene newScene = new Scene(root, width, height);
            newScene.getStylesheets().add(getClass().getResource("/app.css").toExternalForm());
            stage.setScene(newScene);
            stage.setTitle(title);
            stage.show();
        } catch (Exception e) {
            e.printStackTrace(); // good enough for debugging
        }
    }
    /**
     * Handles the navigation when the user selects the
     * "Order Coffee" option from the main menu.
     *
     * @param event the action event generated by clicking the coffee button
     */
    @FXML
    private void onOpenCoffee(ActionEvent event) {
        switchView("coffee-view.fxml", "Ordering Coffee", event);
    }
    /**
     * Handles the navigation when the user selects the
     * "Order Donuts" option from the main menu.
     *
     * @param event the action event generated by clicking the donuts button
     */
    @FXML
    private void onOpenDonuts(ActionEvent event) {
        switchView("donut-view.fxml", "Ordering Donuts", event);
    }
    /**
     * Handles the navigation when the user selects the
     * "Order Sandwich" option from the main menu.
     *
     * @param event the action event generated by clicking the sandwich button
     */
    @FXML
    private void onOpenSandwich(ActionEvent event) {
        switchView("sandwich-view.fxml", "Ordering Sandwich", event);
    }
    /**
     * Handles the navigation when the user selects the
     * "Current Order" option from the main menu.
     *
     * @param event the action event generated by clicking the current order button
     */
    @FXML
    private void onOpenCurrentOrder(ActionEvent event) {
        switchView("current-order-view.fxml", "Current Order", event);
    }
    /**
     * Handles the navigation when the user selects the
     * "Store Orders" option from the main menu.
     *
     * @param event the action event generated by clicking the store orders button
     */
    @FXML
    private void onOpenStoreOrders(ActionEvent event) {
        //THIS MUST MATCH YOUR FXML FILE NAME
        switchView("all-orders-view.fxml", "Store Orders", event);
    }
}
